theme = "edge_custom"

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "position-percentage"]

[editor.indent-guides]
render = true
character = "╎"

[editor.whitespace]
render = true
character = "•"
